--2024-10-25 10:33:33--  https://raw.githubusercontent.com/majid-2002/cd/main/2.l
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1071 (1.0K) [text/plain]
Saving to: ‘2.l.1’

     0K .                                                     100% 23.2M=0s

2024-10-25 10:33:36 (23.2 MB/s) - ‘2.l.1’ saved [1071/1071]

